application: cambridge-challenge
version: 0-3
runtime: go
api_version: 2
handlers:

# redirect appengine login_required to our Login handler (for openid, needed when a login: required is set below)
- url: /_ah/login_required
  script: _go_app

# no login required for /Login/
- url: /Login/
  script: _go_app

# go handles all other URLs
- url: /.*
  script: _go_app

# static serving of stylesheets
- url: /stylesheets
  static_dir: static/stylesheets

# default skip_files
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*

